// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-05-30 11:12:53

package com.google.samples.apps.sunflower;

import com.alipay.mobile.framework.service.ext.annotation.CheckLogin;
import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;


public interface HTTP_API_Group1Client {


    @SignCheck
    @OperationType("com.google.samples.apps.sunflower.opt1.http")
    public String flowerGetnameGet ();


}